### ISSUE TITLE
Add support for Nextcloud Login Flow?

### ISSUE THREAD

**Issue by e-alfred** [fds2610/NCT-Desktop#10]
Hello,

to make the login easier without manually setting a password and username it would be nice to add the Login Flow v2 authentication method to this app:

https://docs.nextcloud.com/server/18/developer_manual/client_apis/LoginFlow/index.html?highlight=login%20flow#login-flow-v2

**Comment by fds2610** [comment]
good hint. will take a while to complete.

**Comment by fds2610** [comment]
just added this to 0.1.0 beta. you can download binaries in a view minutes. @e-alfred pls test it on your side...

**Comment by Refhi** [comment]
Commented here : 
(spoiler : it works, but not yet perfectly user-friendly)
https://github.com/fds2610/NCT-Desktop/pull/16#issuecomment-636849628

**Comment by fds2610** [comment]
so, as everybody is fine with this one I will merge this now. thanks a lot for your help !
