### ISSUE TITLE
Keep non-talk notifications

### ISSUE THREAD

**Issue by Refhi** [fds2610/NCT-Desktop#14]
Not an issue but a strong whish on my side :
I figured as it's called "NextCloud Talk" you might want to make the notifications "talk-only"

I like the way it works today as I can sent admin notifications through the occ command to all my co-workers

So if one day you make the notifications "talk-only" could you make it optionnal ?

**Comment by fds2610** [comment]
interesting aspect. i will keep in mind and this fr (feature request) open.

**Comment by fds2610** [comment]
to specify the todo, here:
I want to add a configurable option to select the behavior to show only Talk notification (default) or also show (all) other notifications...

**Comment by fds2610** [comment]
done this with v0.1.3.
