### ISSUE TITLE
[Enhancement] Open Spreed url by default if no notification

### ISSUE THREAD

**Issue by Baccanno** [fds2610/NCT-Desktop#18]
https://github.com/fds2610/NCT-Desktop/blob/eeb19cd935ca932ddc292516d73290edd4670455/nct.js#L70
Shouldn't the mLink default url be NC talkURL ? for now it opens base NC page, and you have to click on the talk button.

**Comment by fds2610** [comment]
Hi @Baccanno , yes and no. mLink takes Base-URL as a default as long as we received no notification. As soon as the notification is received, mLink gets updated and will keep directing us to Talk (last conversation).
I COULD look for some Talk-URL and set that in future... :-)

**Comment by fds2610** [comment]
wie wäre es, "/index.php/apps/spreed/" einfach anzuhängen als Default ?

**Comment by Baccanno** [comment]
I believe it is yes

**Comment by Baccanno** [comment]
> Hi @Baccanno , yes and no. mLink takes Base-URL as a default as long as we received no notification. As soon as the notification is received, mLink gets updated and will keep directing us to Talk (last conversation).
> I COULD look for some Talk-URL and set that in future... :-)

Yes I was indeed talking about the state where there is no notification. It would actually even be better if it could the "last" notified conversation.

**Comment by fds2610** [comment]
well, this is not so complicated:
a) the base-url is fixated in the config-input-field.
b) with CURRENT release of nextcloud to me it seems that Talk can be reached pretty sure by adding "/index.php/apps/spreed/" to the base url
c) with every Talk-notification i receive an individual link directly to that message in that conversation

as I understand you, you would rather jump to b) at any time than using c) as soon as it was set or make it a configurable behavior ?

**Comment by Baccanno** [comment]
- I'd like to jump to C (last notified message) whenever I can.
- I could jump to B as a fallback. But I'd rather jump to my first stared conversation or "Last active"

I believe it should be the default behaviour as it does not add more clicks if you want to do another action. So no need to make it configurable for now I guess.

**Comment by fds2610** [comment]
@Baccanno do you use my sourcecode or do you need a "compiled" zip to test ?
I added this change to the branch new-login-flow but did not create a zip file, yet.

**Comment by Baccanno** [comment]
I'm using the compiled version having no electron setup locally. I might do it in the future. Would be quite interesting for everybody, yourself included, to have a CI running in order to always have the last built test automatically available.

**Comment by Baccanno** [comment]
I actually found this repo that seems to make the process painless ! https://github.com/samuelmeuli/action-electron-builder

**Comment by fds2610** [comment]
@Baccanno thanks for your contribution which i really appreciate! currently i try to understand github&git so it is ok for me to compile everything manually, but I will keep your hint in mind. maybe we should open a separate issue for that!
in the meanwhile i compiled a version for you: https://code.schepmann.de/NCT-Desktop/nct-desktop-win32-ia32-Baccanno.zip :-)

**Comment by fds2610** [comment]
well i implemented this issue in 0.1.1 Beta ( #19 branch) , please test. all binaires are uploaded and ready for testing.

**Comment by Baccanno** [comment]
The configuration work as expected but the wording is misleading :
"default to base-url instead of NC-Talk directly"  should be "Default to NC-Talk instead of base URL" 
(When checked it actually redirects to NC-Talk)

**Comment by Baccanno** [comment]
> * I'd like to jump to C (last notified message) whenever I can.
> * I could jump to B as a fallback. But I'd rather jump to my first stared conversation or "Last active"

Tell me if you need other feedback for the follow up. I wasn't able to test notifcation locally with a 2nd account and private navigation. No notification are received from Spreed itself. I wonder why

**Comment by Baccanno** [comment]
I can confirm that notification are not showing up anymore on the latest build.

**Comment by fds2610** [comment]
d*mn... it is always this last little hot fix one implements after Q and regression tests... i updated& uploaded all binaires....

**Comment by Baccanno** [comment]
Okay, last test I did was good :
- Opens Spreed app by default on double click
- Opens last conversation if any on double click
- Notification seem to works

Great additions 👍

**Comment by fds2610** [comment]
as this and issue #17 seem to work now. i close both and merge it all, now. Thanks for testing @all !
