### ISSUE TITLE
CI for automatique builds and release, Github Action

### ISSUE THREAD

**Issue by Baccanno** [fds2610/NCT-Desktop#20]
I actually found this repo that seems to make the process painless ! https://github.com/samuelmeuli/action-electron-builder

It seems you'll just have to tag your releases like this "git tag 1.0.X RCX && git push --tags" and it will automatically create a build. 

I'll put that in another issue if you feel like it.

_Originally posted by @Baccanno in https://github.com/fds2610/NCT-Desktop/issues/18#issuecomment-638872836_

**Comment by Baccanno** [comment]
Other things that increase the need of the CI : it will be much more effective for feedback to be able to say which build we're using.  Maybe just add the date of your build in the meantime 

I'd advise and I personally like the (YYYY.MM.DD.LetterForBuildOfTheDay) format, very easy to order/understand and look for.
(Ex: 2020.06.05.A, if you make another one the same day 2020.06.05.B, the day after 2020.06.06.A, etc)

**Comment by fds2610** [comment]
@Baccanno i am currently integrating this CI tools which might change the way i am currently working quite a bit. Unfortunately there seem to be some limitations regarding linux&mac building. I totally understand your remark about versioning, and i will adopt this quite soon. let me introduce this method:
V.x.y.z-build-ymmddL which means I stick on my previous versioning plus I add the current date in shortest possible format (last digit of year-month-day) and then append a letter for the daily build.
This could result in todays manual build like: 0.1.2-build-00611A

**Comment by Baccanno** [comment]
Well, any named version is already quite good. Thanks for considering it

**Comment by fds2610** [comment]
first windows build seems to work smoothly.

**Comment by Baccanno** [comment]
I had a look at the action, looks great. I can't see where the release/artifacts are created ? The publishing step seems to fail.

**Comment by Baccanno** [comment]
```• publishing      publisher=Github (owner: fds2610, project: NCT-Desktop, version: 0.1.3-build-00611A)
  • uploading       file=NCT-Notifier-Setup-0.1.3-build-00611A.exe.blockmap provider=GitHub
  • uploading       file=NCT-Notifier-Setup-0.1.3-build-00611A.exe provider=GitHub
  • GitHub release not created  reason=existing type not compatible with publishing type tag=v0.1.3-build-00611A version=0.1.3-build-00611A existingType=release publishingType=draft
  • skipped publishing  file=NCT-Notifier-Setup-0.1.3-build-00611A.exe.blockmap reason=existing type not compatible with publishing type tag=v0.1.3-build-00611A version=0.1.3-build-00611A existingType=release publishingType=draft
  • skipped publishing  file=NCT-Notifier-Setup-0.1.3-build-00611A.exe reason=existing type not compatible with publishing type tag=v0.1.3-build-00611A version=0.1.3-build-00611A existingType=release publishingType=draft
  • skipped publishing  file=latest.yml reason=existing type not compatible with publishing type tag=v0.1.3-build-00611A version=0.1.3-build-00611A existingType=release publishingType=draft```

**Comment by Baccanno** [comment]
I tried the build in the release section. It installs and launch correctly. Great

**Comment by fds2610** [comment]
works for windows only.
