### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by Refhi** [fds2610/NCT-Desktop#23]
When starting the lastest windows binary ( downloaded this morning so I guess it's 0.1.4-build-00613A ?)

![image](https://user-images.githubusercontent.com/2778215/85693584-a83c4480-b6d6-11ea-929b-220c8b668d68.png)

Best regards,
[edit] even if nothing shows after clicking ok, a process stays on in the windows manager and processes keep pilling up if I keep trying to start the app

**Comment by fds2610** [comment]
due to ignoring /dist/ important files were ignored, too.

**Comment by fds2610** [comment]
updated packaging scripts and recompiled all three zip files. for me it works...
