### ISSUE TITLE
secure local torage of credentials

### ISSUE THREAD

**Issue by fds2610** [fds2610/NCT-Desktop#24]
currently server-url, userid, and APP-Password is stored unencrypted in a local file config.ini.
i want to store this information more secure as I do not want other applications being able to access this.

Any help appreciated on how to encrypt/store this kind of information as i have no clue how to resolve this issue, yet.

**Comment by fds2610** [comment]
after having talked to some pro sw developers i came to the conclusion that there is no secure local storage possibilityexept encrypting and using a user-defined password. as i do not want to make things others can do better, i will not implement a key-storage on my own. I will add an option that users can re-enter their passwords on startup OR store them in the current way. Please comment your thoughts about this! all opinions are welcome !

**Comment by Refhi** [comment]
Mmmmmm could the windows credential manager be a lead ? I think they might encrypt the stored passwords before session opening ?

Otherwise as long as the stored password is just an "application" password and not the main one I believe it ease the problem

**Comment by fds2610** [comment]
Hi @Refhi thanks for your hint, but i agree that an app password should not be the problem. I do not want to over-engineer this as the main nextcloud desktop client App does not care about this topic either, yet.
So i will leave the status quo until further notice.
