### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by plyaskin** [fds2610/NCT-Desktop#27]
Hi! 
Thank you for the app but could you explain how I can install this one to my PC (win 10)?

**Comment by fds2610** [comment]
Hi,
as I mentioned in README.md:
Furthermore I decided to provide experimental, unsigned binaries. MAC OSX here: code.schepmann.de/NCT-Desktop/nct-desktop-darwin-x64.zip Win x64 here: code.schepmann.de/NCT-Desktop/nct-desktop-win32-ia32.zip Lin x64 here: code.schepmann.de/NCT-Desktop/nct-desktop-linux-x64.zip
The other option is, you install Electron and clone my git repo.

**Comment by plyaskin** [comment]
Sorry, but I'm not a developer and don't know how it works.
How I can find you in Electron? Or how I can compile your sources to exe-file?

**Comment by fds2610** [comment]
Hi, 
download the files here: code.schepmann.de/NCT-Desktop/nct-desktop-win32-ia32.zip
unzip into a folder and start the .exe.
