### ISSUE TITLE
open browser into NC talk session if clicked on according ballon notification

### ISSUE THREAD

**Issue by fds2610** [fds2610/NCT-Desktop#4]
As a user, if i receive a notification-ballon I want to click on that and directly open a browser windows withe the notified chat/talk/event to ease up workflow.

**Comment by fds2610** [comment]
i tried to open the event's link in an electron browserwindow, loading the corresponding URL given within the event, though the browser window stays within login-panel without logging into NC. I assume it does not handle alls HTTP 301 redirection commands from the server correctly. If somebody knows, how to handle this with nextcloud correctly, any hint is well appreciated.
I already began reading into this [https://docs.nextcloud.com/server/latest/developer_manual//client_apis/LoginFlow/index.html](https://docs.nextcloud.com/server/latest/developer_manual//client_apis/LoginFlow/index.html) but it will need more effort...

**Comment by e-alfred** [comment]
Can you make a new branch in your repository with the electron browser enabled?

**Comment by fds2610** [comment]
@e-alfred ok, ill give it a try...

**Comment by e-alfred** [comment]
I tried to run your browser-window branch but I couldn't open a browser window using the context menu or clicking on the tray icon. The context menu only shows "configure" and "quit" it seems.

**Comment by fds2610** [comment]
@e-alfred the browser window will open as soon as you click on the notification-ballon.

**Comment by fds2610** [comment]
be sure do have the right branch downloaded. in 0.0.6 in nct.js line 361 there should be a funcion-call for 			createTalkWindow(link);
this is the only difference between the two branches right now. for me it opens the window.

**Comment by e-alfred** [comment]
Yes, it works now after a reboot of my client. I also don't have your strange redirection problem mentioned earlier, it works as expected. Now Talk has its own desktop client! :rocket: :smiley:

Maybe somebody from @nextcloud is interested in this like @nickvergessen?

**Comment by fds2610** [comment]
great, how is your setup? I guess:
- Chrome or Chromium installed?
- you saved passwords in your browser?

**Comment by fds2610** [comment]
i deleted the branch "browser-window" and implemented interim-solution into master-branch.

**Comment by e-alfred** [comment]
Nice, can you add something like double click and a menu option in the context menu to be able to open the browser window if no notification is sent to access the chat window quickly?
