### ISSUE TITLE
App on macOS does not open

### ISSUE THREAD

**Issue by tiiiecherle** [fds2610/NCT-Desktop#5]
Thanks for picking this up.

We would very much like to use a desktop app for nextcloud talk on macOS 10.15.4 with working notifications.

The current version on macOS does not start just with the message `The app can not be opened`.

Thanks for the project and for looking into the issue.

**Comment by fds2610** [comment]
@tiiiecherle can you give little more details on the error ? is there any systemlog or other detailed error message? I guess you dont have electron installed ?

**Comment by tiiiecherle** [comment]
Hey, 

when I double-click the `nct-desktop.app` the only thing that happens is that this window opens:

![Bildschirmfoto 2020-04-12 um 19 30 58](https://user-images.githubusercontent.com/7059936/79075639-6bc29480-7cf4-11ea-8159-f2754cf9005d.jpg)

It only says (in German) that the app `nct-desktop.app` can not be opened.

**Comment by tiiiecherle** [comment]
If I do 
`chmod +x /Users/"$USER"/Desktop/files/nct-desktop-darwin-x64/nct-desktop.app/Contents/MacOS/nct-desktop`
and then open the file in a terminal I get an error similar to yours.

According to [this](https://github.com/electron/electron/issues/10702) and the referring links it has something to do with `npm` on your end before building.

Hope this helps a bit.

**Comment by tiiiecherle** [comment]
After some more research it seems the first problem `The app can not be opened` results from bad extraction of the zip archive and distributing via dmg is recommended to permissions. If I extract with default archiver I get the issue, if I unzip with keka the first issue is gone.

**Comment by fds2610** [comment]
unfortunately i have no access to a mac. is there anybody with a mac and an installed electron dev environment ?

**Comment by fds2610** [comment]
as @sb0stn added an icon for MAC usage, I suppose the app is now running on a mac also...
