### ISSUE TITLE
Linux port ?

### ISSUE THREAD

**Issue by Refhi** [fds2610/NCT-Desktop#6]
Would it be possible to easily make a Linux port? (I use Ubuntu a lot)

(I'm not sure this question should be posted here so my apologies if it's not the right place to do so)

**Comment by fds2610** [comment]
@refhi no need to apologize for polite questions ;-) unfortunately i am quite new to electron and not yet able to compile for any other OS than windows. MAC package does not run right now.
If you install electron environment on you ubuntu it should be no big deal to compile one for linux. unfortunately i currently have no time to do this. maybe in a week or so. anybody familiar with electron on linux is welcome to compile it for us, I might host it.
sorry for that answer for now.

**Comment by e-alfred** [comment]
I run it on (Debian) Linux and it runs pretty well. Be sure to install Node.JS V13 using the official repository and then clone this Github repositroy. Then run the following commands in the directory you cloned:

```
npm install electron
node_modules/electron/dist/electron . --no-sandbox
```

**Comment by fds2610** [comment]
@e-alfred can you compile it and host the binary? I can add your url to the readme, then.

**Comment by e-alfred** [comment]
It seems like the tray messages are not shown on a KDE desktop at least. Maybe it would be better to rely on node-notifier for tray messages?

https://www.npmjs.com/package/node-notifier

**Comment by fds2610** [comment]
nice idea, @e-alfred ! I will give it a try.
btw. I compiled a linux-version, too now !

**Comment by e-alfred** [comment]
`tray.displayBalloon` is not supported under Linux: https://github.com/electron/electron/issues/13527#issuecomment-401671290

Another change that would be a good idea is to not package the configuration information into a distributed app and make the password field in the configuration dialog show only *** instead of the password.

**Comment by e-alfred** [comment]
> further more i shows "SnoreToast" Icon and source. I will have to review this tool more deeply...

Snoretoast seems to be related to the appid: https://www.npmjs.com/package/node-notifier#windows-snoretoast-text

**Comment by fds2610** [comment]
updated with electron-notification API instead of tray.Balloon.
does it work in linux now ?

**Comment by e-alfred** [comment]
Notification seem to work now, can you add the latest changes to the browser-window branch too?

**Comment by fds2610** [comment]
done.

**Comment by e-alfred** [comment]
I tried the browser-window branch and it seems like the browser window does not open up if I click the notification. Here is what the log says:

```
STATUS: 200
Sub: User hat eine Nachricht in der Unterhaltung room gesendet
Msg: test
Link: https://server/call/45423432
Link: https://server/call/45423432
Balloon fired. 
STATUS: 200
```

**Comment by fds2610** [comment]
hello @e-alfred , can you check you have downloaded the right code? in nct.js in line 361 there should be the function-call "createTalkWindow". to me it works... logging should be the same. I just added this one line in that branch...
